info:
  title: Pastebin API
  version: '1.0'
  description: A simple application to share some python code snippets.
openapi: 3.0.0

tags:
  - name: users
    description: Operations related to users
  - name: snippets
    description: Operations related to user snippets

paths:
  /users/:
    get:
      tags:
        - users
      description: Returns the list of users
      responses:
        '200':
          description: Returns a json array of users
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Users'
    post:
      tags:
        - users
      description: Create a new user and returns its information
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: Returns user information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          $ref: '#/components/responses/BadRequest'
    patch:
      tags:
        - users
      security:
        - BasicAuth: []
      description: Update user properties. You can update one or multiple properties at the same time.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: Returns updated user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
    delete:
      tags:
        - users
      security:
        - BasicAuth: []
      description: Deletes a user
      responses:
        '204':
          $ref: '#/components/responses/DeleteResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
          example: 1
        email:
          type: string
          example: foo@bar.com
        password:
          type: string
          writeOnly: true
          minLength: 4
          maxLength: 100
          example: hello
        pseudo:
          type: string
          minLength: 2
          maxLength: 100
          example: foobar
        first_name:
          type: string
          minLength: 2
          maxLength: 100
          example: foo
        last_name:
          type: string
          minLength: 2
          maxLength: 100
          example: bar
        created_at:
          type: string
          format: datetime
          description: datetime represented in iso format
          example: '2020-06-20T23:15:32'
          readOnly: true
      required:
        - id
        - email
        - password
        - pseudo
        - first_name
        - last_name
        - created_at
    Users:
      type: array
      items:
        $ref: '#/components/schemas/User'
    SimpleError:
      type: object
      properties:
        detail:
          type: string
          description: |
            a message indicating whether the resource is not found, forbidden or unauthorized depending of the response
            status code
      required:
        - detail

  responses:
    NotFound:
      description: The specified resource was not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SimpleError'
    Forbidden:
      description: The specified resource is forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SimpleError'
    Unauthorized:
      description: The specified resource is unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SimpleError'
    BadRequest:
      description: The payload is incorrect
      content:
        application/json:
          schema:
            type: object
            properties:
              detail:
                type: object
                properties:
                  errors:
                    type: object
                  input:
                    type: object
                required:
                  - errors
                  - input
            required:
              - detail
    DeleteResponse:
      description: The resource was deleted

  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic