"""added column created_at in group_permissions and user_permissions tables

Revision ID: 89175538a1bc
Revises: b7951e5e91c8
Create Date: 2020-06-10 21:51:02.044503

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.

revision = '89175538a1bc'
down_revision = 'b7951e5e91c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_permissions',
                  sa.Column('created_at', sa.DateTime(), nullable=False, server_default='2020-06-10 20:01:29.334389'))
    op.add_column('user_groups',
                  sa.Column('created_at', sa.DateTime(), nullable=False, server_default='2020-06-10 20:01:29.334389'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_groups', 'created_at')
    op.drop_column('group_permissions', 'created_at')
    # ### end Alembic commands ###
