"""added User, Group and Permission models with linked tables

Revision ID: b7951e5e91c8
Revises: 
Create Date: 2020-06-08 22:01:15.907931

"""
from alembic import op
import sqlalchemy_utils
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'b7951e5e91c8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_groups'))
                    )
    op.create_table('permissions',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions'))
                    )
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('first_name', sa.String(length=100), nullable=False),
                    sa.Column('last_name', sa.String(length=100), nullable=False),
                    sa.Column('pseudo', sa.String(length=100), nullable=False),
                    sa.Column('email', sqlalchemy_utils.types.email.EmailType(length=255), nullable=False),
                    sa.Column('password', sa.String(length=200), nullable=False),
                    sa.Column('admin', sa.Boolean(), nullable=False),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
                    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_pseudo'), 'users', ['pseudo'], unique=True)
    op.create_table('group_permissions',
                    sa.Column('group_id', sa.Integer(), nullable=False),
                    sa.Column('permission_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['group_id'], ['groups.id'],
                                            name=op.f('fk_group_permissions_group_id_groups')),
                    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'],
                                            name=op.f('fk_group_permissions_permission_id_permissions')),
                    sa.PrimaryKeyConstraint('group_id', 'permission_id', name=op.f('pk_group_permissions'))
                    )
    op.create_table('user_groups',
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('group_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_user_groups_group_id_groups')),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_groups_user_id_users')),
                    sa.PrimaryKeyConstraint('user_id', 'group_id', name=op.f('pk_user_groups'))
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_groups')
    op.drop_table('group_permissions')
    op.drop_index(op.f('ix_users_pseudo'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('permissions')
    op.drop_table('groups')
    # ### end Alembic commands ###
